# Generated by Django 2.2.11 on 2020-04-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='main_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2000)),
                ('backgroundimage', models.ImageField(upload_to='dynamic_pics')),
            ],
        ),
    ]
